service: node10-unix-utils 
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: us-east-1

layers:
  lambci-nodejs10:
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - nodejs10.x
